### ISSUE TITLE
Installed successfully ! Still not working ! 

### ISSUE THREAD

**Issue by ashwinkhode** [dakyskye/coc-cord#4]
Tried `:checkhealth` everything is fine there
Still activity not showing on discord ! Please help !

**Comment by dakyskye** [comment]
I need more information.
1) What's your operating system?
2) What's your coc.nvim version?
3) Do you use official Discord client?
4) Do you get any output that says 'coc-cord is trying to connect to Discord gateway'?
5) Is `coc-cord` actually added in `~/.config/coc/extensions/package.json`?

If you have positive answers to the last three questions, try to run `npm install` in `~/.config/coc/extensions/node_modules/coc-cord/` drectory.

**Comment by ashwinkhode** [comment]
OS : Windows 10
coc.nvim v0.0.78
I use Official Discord Client
No I do not get any output on discord 
Usually my vim files are in Users and AppData folder but I cant find this directory anywhere

**Comment by dakyskye** [comment]
> No I do not get any output on discord

I mean output in NeoVim.

> Usually my vim files are in Users and AppData folder but I cant find this directory anywhere

There must be a folder coc somewhere.

**Comment by ashwinkhode** [comment]
No output in NeoVim either ! I tried `checkhealth`  and here's a screenshot of that
I found that folder, tried npm install also ! still its not working ! :(
![Annotation 2020-07-15 011250](https://user-images.githubusercontent.com/53361996/87469479-fd65d900-c638-11ea-9290-538d0ef23fc7.jpg)
![Annotation 2020-07-15 012025](https://user-images.githubusercontent.com/53361996/87469779-6e0cf580-c639-11ea-81c1-11114c863844.jpg)
![Annotation 2020-07-15 012043](https://user-images.githubusercontent.com/53361996/87469787-6fd6b900-c639-11ea-87b7-2023b2ea808f.jpg)

**Comment by dakyskye** [comment]
Hm, that's weird. It works well on my GNU/Linux machine.

**Comment by dakyskye** [comment]
@ashwinkhode I am working on 0.4.0 version, adding more languages. I will push the changes in a couple of minutes, so it will work.

**Comment by dakyskye** [comment]
Should be working now.

**Comment by dakyskye** [comment]
OK now it works, but `CocCommand cord.version` says it's version 0.3.1, which is wrong, but that's my fault. I forgot to update a file before I published the package. Just nevermind it, coc.version can say it's 0.3.1, but it's 0.4.0 already. For next versions, that won't be a case :+1:

**Comment by ashwinkhode** [comment]
Thank you @dakyskye you are doing a great job !
